# Generated by Django 6.1 on 2026-09-16 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0003_library_remote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('missing_in_service', 'missing_in_service'), ('missing_on_disk', 'missing_on_disk')], max_length=32)),
                ('key', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='libraries.library')),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(fields=('library', 'kind', 'key'), name='uniq_discrepancy_library_kind_key')],
            },
        ),
    ]
