# Generated by Django 6.1 on 2026-09-06 13:58

from django.db import migrations

import apps.services.fields


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_service_options_service_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="api_key",
            field=apps.services.fields.EncryptedTextField(blank=True),
        ),
    ]
