# Generated by Django 6.1 on 2026-09-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('kavita', 'Kavita'), ('lanraragi', 'LANraragi')], default='kavita', max_length=32),
        ),
    ]
