# Generated by Django 6.1 on 2026-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_health_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
