# Generated by Django 6.1 on 2026-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_last_health_ok_service_last_polled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
