# Generated by Django 6.1 on 2026-09-14 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_poll_interval_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='poll_interval_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
