# Generated by Django 6.1 on 2026-09-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0007_service_poll_interval_min_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('root_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='services.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1024)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_bytes', models.PositiveBigIntegerField(default=0)),
                ('newest_mtime', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_items', to='libraries.library')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('item_count', models.PositiveIntegerField()),
                ('total_bytes', models.PositiveBigIntegerField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='libraries.library')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='uniq_library_service_name'),
        ),
        migrations.AddIndex(
            model_name='diskitem',
            index=models.Index(fields=['library', 'seen_at'], name='libraries_d_library_8cf821_idx'),
        ),
        migrations.AddConstraint(
            model_name='diskitem',
            constraint=models.UniqueConstraint(fields=('library', 'relative_path'), name='uniq_diskitem_library_path'),
        ),
    ]
