# Generated by Django 6.1 on 2026-09-16 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_library_diskitem_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='scan_interval_seconds',
            field=models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
