# Generated by Django 6.1 on 2026-09-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_scan_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='remote_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
